project:
  type: website
  output-dir: docs

website:
  title: "Hudson Miller"
  sidebar:
    style: "docked"
    search: false
    contents:
    - href: index.qmd
      text: Home
    - about.qmd
    - Lab 2/Lab2WriteUp.qmd
    - Lab 3/Lab3WriteUp.qmd
    - Lab 4/Lab4WriteUp.qmd
    - Lab 5-6/Lab5WriteUp.qmd
    - Lab 8-9/Lab8WriteUp.qmd
    - Lab 10/Lab10WriteUp.qmd
    - Lab 11/Lab11WriteUp.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto



