<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab Thirteen – Statistical Inference – Hudson Miller</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ab8bc71f45afde97538d8ceca41e9436.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Hudson Miller</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Lab 2/Lab2WriteUp.html">Math 240 Labs</a></li><li class="breadcrumb-item"><a href="../Lab 13/Lab13WriteUp.html">Lab 13</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Math 240 Labs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 2/Lab2WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 3/Lab3WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 4/Lab4WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 5-6/Lab5WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 5–6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 8-9/Lab8WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 8–9</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 10/Lab10WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 11/Lab11WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab 11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab 13/Lab13WriteUp.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lab 13</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Colgate Rowing Data Analysis/CMROW_DATA_ANALYSIS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rowing Data Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#remaining-portfolio-work" id="toc-remaining-portfolio-work" class="nav-link active" data-scroll-target="#remaining-portfolio-work"><span class="header-section-number">1</span> Remaining Portfolio Work!</a></li>
  <li><a href="#statistical-inference" id="toc-statistical-inference" class="nav-link" data-scroll-target="#statistical-inference"><span class="header-section-number">2</span> Statistical Inference</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a"><span class="header-section-number">2.1</span> Part a</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b"><span class="header-section-number">2.2</span> Part b</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c"><span class="header-section-number">2.3</span> Part c</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d"><span class="header-section-number">2.4</span> Part d</a></li>
  <li><a href="#part-e" id="toc-part-e" class="nav-link" data-scroll-target="#part-e"><span class="header-section-number">2.5</span> Part e</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab13WriteUp.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Lab 2/Lab2WriteUp.html">Math 240 Labs</a></li><li class="breadcrumb-item"><a href="../Lab 13/Lab13WriteUp.html">Lab 13</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Lab Thirteen – Statistical Inference</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p></p>
<p></p>
<section id="remaining-portfolio-work" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Remaining Portfolio Work!</h1>
<p><strong>By 5p 4/27</strong> Email me a link to your GitHub page with all polished labs rendered, and your review material (at least one unit). In the email, you should include a reflection about the processes involved in creating this portfolio and what you learned as a result. If you’re having trouble reflecting, consider Fink’s Taxonomy of Significant Learning (Google Fink taxonomy aligned self-reflection questions). In the email, let me know whether you would be comfortable sharing your page – I’m hoping that together we can get a good study guide for the final.</p>
</section>
<section id="statistical-inference" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Statistical Inference</h1>
<p><span class="citation" data-cites="Kasdin25">Kasdin et al. (<a href="#ref-Kasdin25" role="doc-biblioref">2025</a>)</span> show that dopamine in the brains of young zebra finches acts as a learning signal, increasing when they sing closer to their adult song and decreasing when they sing further away, effectively guiding their vocal development through trial-and-error. This suggests that complex natural behaviors, like learning to sing, are shaped by dopamine-driven reinforcement learning, similar to how artificial intelligence learns. You can find the paper at this link: <a href="https://www.nature.com/articles/s41586-025-08729-1">https://www.nature.com/articles/s41586-025-08729-1</a>.</p>
<p>Note that the measurement is rather complicated. First, the measurements are taken on syllables of a bird song. When discussing bird songs, the term syllable refers to a single, distinct, uninterrupted sound that is part of a possibly complex bird song.</p>
They initially describe their measurement as follows. They compare the sound of the developing zebra finches to the median sound of adult zebra finches, that act as a “goal” sound.
They contextualize that measurement by computing a “relative quality” that takes into account their current ability (e.g., are they getting closer or further compared to their previous 14 renditions).
They define the “closer” measurements as the 10% of syllable renditions with the highest relative quality and the “further” as the lowest 10%.
<p>Note that the data are measures of dopamine change, they use fibre photometry, changes in the fluorescence indicate dopamine changes in realtime. Their specific measurement considers the percent change in flourescence in 100-ms windows between 200 and 300 ms from the start of singing, averaged across development.</p>
Finally, the researchers note that they adjust the observations to correct for the increased dopamine for singing at all (whether it is close or far).
<p>So, the random variables we are working with are: <span class="math display">\[\begin{align*}
X_{\text{close}} &amp;= \text{average \% change in fluorescence for the top 10\% syllable renditions} \\
&amp;\quad \text{relative to distance from adult sound (corrected for singing)} \\[1ex]
X_{\text{far}} &amp;= \text{average \% change in fluorescence for the bottom 10\% syllable renditions} \\
&amp;\quad \text{relative to distance from adult sound (corrected for singing)}
\end{align*}\]</span></p>
<p>That is, the unit of measure is the syllable as measured on six birds, and the measurement is somewhat complicated.</p>
<section id="part-a" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="part-a"><span class="header-section-number">2.1</span> Part a</h2>
<p>Using the <code>pwr</code> package for <span class="citation" data-cites="pwr">(<a href="#ref-pwr" role="doc-biblioref">Champely 2020</a>)</span>, conduct a power analysis. How many observations would the researchers need to detect a moderate-to-large effect (<span class="math inline">\(d=0.65\)</span>) when using <span class="math inline">\(\alpha=0.05\)</span> and default power (0.80) for a two-sided one sample <span class="math inline">\(t\)</span> test.</p>
<p><strong>Solution</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>(<span class="at">power =</span> <span class="fu">pwr.t.test</span>(</span>
<span id="cb1-2"><a href="#cb1-2"></a>  <span class="at">n =</span> <span class="cn">NULL</span>, <span class="at">d =</span> <span class="fl">0.65</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>, </span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="at">type =</span> <span class="st">"one.sample"</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     One-sample t test power calculation 

              n = 20.58039
              d = 0.65
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># graph if i have time</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
<p>The researchers should have at least 21 observations.</p>
</section>
<section id="part-b" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="part-b"><span class="header-section-number">2.2</span> Part b</h2>
<p>Click the link to go to the paper. Find the source data for Figure 2. Download the Excel file. Describe what you needed to do to collect the data for Figure 2(g). Note that you only need the <code>closer_vals</code> and <code>further_vals</code>. Ensure to <code>mutate()</code> the data to get a difference (e.g., <code>closer_vals - further_vals</code>).</p>
<p><strong>Solution</strong></p>
<p>To get the data for Figure 2(g), I downloaded the source data into an unweildly and very large Excel file. Only a small subset of these data were needed. I copied the <code>closer.vals</code> data to the <code>further.vals</code> sheet, and then exported that sheet to this lab in my Mac files. Now, I have the data locally and it will be easy to keep track of in the future.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>dat.kasdin <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"CompStatLab13Data.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">head</span>(dat.kasdin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Farther.vals Closer.vals
1  -0.22356329  0.35598310
2  -0.10703255  0.05424353
3  -0.18709396  0.14366417
4  -0.11047283  0.12247571
5  -0.17000567  0.10870189
6  -0.08973481  0.31833828</code></pre>
</div>
</div>
<p></p>
</section>
<section id="part-c" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="part-c"><span class="header-section-number">2.3</span> Part c</h2>
<p>Summarize the data.</p>
<ul>
<li>Summarize the further data. Do the data suggest that dopamine in the brains of young zebra finches decreases when they sing further away?</li>
<li>Summarize the closer data. Do the data suggest that dopamine in the brains of young zebra finches increases when they sing closer to their adult song?</li>
<li>Summarize the paired differences. Do the data suggest that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song?</li>
<li><strong>Optional Challenge</strong> Can you reproduce Figure 2(g)? Note that the you can use to plot the range created by adding the mean <span class="math inline">\(\pm\)</span> one standard deviation.</li>
</ul>
<p><strong>Solution</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Farther.vals)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.8</span>, <span class="fl">0.1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb6-4"><a href="#cb6-4"></a>plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-farther" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-farther-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Histogram of Farther Values
</figcaption>
<div aria-describedby="fig-farther-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-farther-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-3"><a href="#cb7-3"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Farther.vals),</span>
<span id="cb7-4"><a href="#cb7-4"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Farther.vals),</span>
<span id="cb7-5"><a href="#cb7-5"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Farther.vals),</span>
<span id="cb7-6"><a href="#cb7-6"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Farther.vals)</span>
<span id="cb7-7"><a href="#cb7-7"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb7-8"><a href="#cb7-8"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb7-9"><a href="#cb7-9"></a>summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-farther.summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-farther.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of the Farther Values
</figcaption>
<div aria-describedby="tbl-farther.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.2128063</td>
<td style="text-align: right;">-0.1880146</td>
<td style="text-align: right;">0.1342712</td>
<td style="text-align: right;">0.0180287</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p></p>
<p>We have preliminary evidence that supports the conjecture that dopamine in the brains of young zebra finches decreases when they sing further away from their adult song- our mean and median are below zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram shows an approximately left-skewed distribution, with some values near zero.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Closer.vals)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb8-4"><a href="#cb8-4"></a>plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-closer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-closer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Histogram of Closer Values
</figcaption>
<div aria-describedby="fig-closer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-closer-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-3"><a href="#cb9-3"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Closer.vals),</span>
<span id="cb9-4"><a href="#cb9-4"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Closer.vals),</span>
<span id="cb9-5"><a href="#cb9-5"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Closer.vals),</span>
<span id="cb9-6"><a href="#cb9-6"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Closer.vals)</span>
<span id="cb9-7"><a href="#cb9-7"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb9-9"><a href="#cb9-9"></a>summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-closer.summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-closer.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary of the Closer Values
</figcaption>
<div aria-describedby="tbl-closer.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.1786241</td>
<td style="text-align: right;">0.1436642</td>
<td style="text-align: right;">0.0975315</td>
<td style="text-align: right;">0.0095124</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p></p>
<p>We have preliminary evidence that supports the conjecture that dopamine in the brains of young zebra finches increases when they sing closer to their adult song- our mean and median are above zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram show some values near zero, with an approximately symmetric distrivution.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>dat.kasdin <span class="ot">=</span>  dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">mutate</span>(<span class="at">Difference =</span> Closer.vals<span class="sc">-</span>Farther.vals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Difference)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">1.1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb11-4"><a href="#cb11-4"></a>plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-diff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Histogram of Differences
</figcaption>
<div aria-describedby="fig-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-diff-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-3"><a href="#cb12-3"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Difference),</span>
<span id="cb12-4"><a href="#cb12-4"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Difference),</span>
<span id="cb12-5"><a href="#cb12-5"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Difference),</span>
<span id="cb12-6"><a href="#cb12-6"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Difference)</span>
<span id="cb12-7"><a href="#cb12-7"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb12-8"><a href="#cb12-8"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb12-9"><a href="#cb12-9"></a>summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-differences.summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-differences.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of the Paired Differences
</figcaption>
<div aria-describedby="tbl-differences.summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.3914303</td>
<td style="text-align: right;">0.3533044</td>
<td style="text-align: right;">0.2140658</td>
<td style="text-align: right;">0.0458241</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p></p>
<p>We have preliminary evidence that supports the conjecture that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song- our mean and median are above zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram shows an approximately uniform distribution, with one slight outlier.</p>
</section>
<section id="part-d" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="part-d"><span class="header-section-number">2.4</span> Part d</h2>
<p>Conduct the inferences they do in the paper. Make sure to report the results a little more comprehensively – that is your parenthetical should look something like: (<span class="math inline">\(t=23.99\)</span>, <span class="math inline">\(p&lt;0.0001\)</span>; <span class="math inline">\(g=1.34\)</span>; 95% CI: 4.43, 4.60). Ensure to verify any conditions for use.<br>
<strong>Note</strong>: Your numbers will vary slightly because they reported two-sided test <span class="math inline">\(p\)</span>-values instead of the specified one-sided tests.</p>
<ul>
<li>“The close responses differed significantly from 0 (<span class="math inline">\(p=1.63 \times 10^{-8}\)</span>).’’<br>
<strong>Note</strong>: Use the appropriate one-sided test.</li>
<li>“The far responses differed significantly from 0 (<span class="math inline">\(p=5.17 \times 10^{-8}\)</span>).’’<br>
<strong>Note</strong>: Use the appropriate one-sided test.</li>
<li>“The difference between populations was significant (<span class="math inline">\(p=1.04 \times10^{-8}\)</span>).’’<br>
<strong>Note</strong>: Use the two-sided test.</li>
</ul>
<p><strong>Solution</strong></p>
<p>For the closer values: we have a sample size of 25 and our data are approximately left-skewed. We really don’t fit the conditions for use, but we are close and it will be good practice, so we will proceed!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="co"># t-test:</span></span>
<span id="cb13-4"><a href="#cb13-4"></a></span>
<span id="cb13-5"><a href="#cb13-5"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dat.kasdin$Closer.vals
t = 9.1573, df = 24, p-value = 1.333e-09
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 0.1452511       Inf
sample estimates:
mean of x 
0.1786241 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># effect size:</span></span>
<span id="cb15-2"><a href="#cb15-2"></a></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |      95% CI
-----------------------
1.77      | [1.24, Inf]

- One-sided CIs: upper bound fixed at [Inf].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># get confidence interval: </span></span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dat.kasdin$Closer.vals
t = 9.1573, df = 24, p-value = 2.665e-09
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.1383650 0.2188831
sample estimates:
mean of x 
0.1786241 </code></pre>
</div>
</div>
<p></p>
<p>We do have statistically discernible support for the hypothesis that dopamine in the brains of young zebra finches increases when they sing closer to their adult song (<span class="math inline">\(t=9.16, p&lt;0.05, g=1.77, 95 \% \hspace{0.15cm} CI : (0.139,0.22)\)</span>).</p>
<p>Now, let’s check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-2"><a href="#cb19-2"></a></span>
<span id="cb19-3"><a href="#cb19-3"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb19-4"><a href="#cb19-4"></a></span>
<span id="cb19-5"><a href="#cb19-5"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-closer2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-closer2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: histogram of the closer resampling values
</figcaption>
<div aria-describedby="fig-closer2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-closer2-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Our data are still skewed. The researchers really should not have done a t-test here, as the conditions for use are not met.</p>
<p>For the further values: we have a sample size of 25 and our data are approximately symmetric. We have somewhat unsure footing, but we will proceed anyway!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb20-2"><a href="#cb20-2"></a></span>
<span id="cb20-3"><a href="#cb20-3"></a><span class="co"># t-test:</span></span>
<span id="cb20-4"><a href="#cb20-4"></a></span>
<span id="cb20-5"><a href="#cb20-5"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dat.kasdin$Farther.vals
t = -7.9245, df = 24, p-value = 1.866e-08
alternative hypothesis: true mean is less than 0
95 percent confidence interval:
       -Inf -0.1668619
sample estimates:
 mean of x 
-0.2128063 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># effect size:</span></span>
<span id="cb22-2"><a href="#cb22-2"></a></span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |        95% CI
-------------------------
-1.53     | [-Inf, -1.04]

- One-sided CIs: lower bound fixed at [-Inf].</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># get confidence interval: </span></span>
<span id="cb24-2"><a href="#cb24-2"></a></span>
<span id="cb24-3"><a href="#cb24-3"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dat.kasdin$Farther.vals
t = -7.9245, df = 24, p-value = 3.731e-08
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -0.2682307 -0.1573819
sample estimates:
 mean of x 
-0.2128063 </code></pre>
</div>
</div>
<p></p>
<p>We do have statistically discernible support for the hypothesis that dopamine in the brains of young zebra finches decreases when they sing further away from their adult song (<span class="math inline">\(t=-7.92, p&lt;0.05, g=-1.53, 95 \% \hspace{0.15cm} CI : (-0.27,-0.16)\)</span>).</p>
<p>Now, let’s check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-2"><a href="#cb26-2"></a></span>
<span id="cb26-3"><a href="#cb26-3"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb26-4"><a href="#cb26-4"></a></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-farther2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-farther2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: histogram of the farther resampling values
</figcaption>
<div aria-describedby="fig-farther2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-farther2-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Our data are still <em>very</em> skewed. The researchers really should not have done a t-test here, as the conditions for use are not met.</p>
<p>For the differences: we have a sample size of 25 and our data are approximately symmetric. We have somewhat unsure footing, but we will proceed anyway!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb27-2"><a href="#cb27-2"></a></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="co"># t-test:</span></span>
<span id="cb27-4"><a href="#cb27-4"></a></span>
<span id="cb27-5"><a href="#cb27-5"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Difference, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dat.kasdin$Difference
t = 9.1428, df = 24, p-value = 2.746e-09
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.3030683 0.4797923
sample estimates:
mean of x 
0.3914303 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># effect size:</span></span>
<span id="cb29-2"><a href="#cb29-2"></a></span>
<span id="cb29-3"><a href="#cb29-3"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Hedges' g |       95% CI
------------------------
1.77      | [1.14, 2.39]</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Note that we already have a valid confidence interval from our original t-test.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
<p>We do have statistically discernible support for the hypothesis that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song (<span class="math inline">\(t=9.14, p&lt;0.05, g=1.77, 95 \% \hspace{0.15cm} CI : (0.303,0.480)\)</span>).</p>
<p>Now, let’s check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-2"><a href="#cb32-2"></a></span>
<span id="cb32-3"><a href="#cb32-3"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb32-4"><a href="#cb32-4"></a></span>
<span id="cb32-5"><a href="#cb32-5"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-diff2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-diff2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: histogram of the resampling values for the differences
</figcaption>
<div aria-describedby="fig-diff2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-diff2-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Our data actually look skewed here as well. So even in this scenario, the researcher should not have done a t-test!</p>
</section>
<section id="part-e" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="part-e"><span class="header-section-number">2.5</span> Part e</h2>
<p>For each hypothesis test in the previous question, plot the null <span class="math inline">\(T\)</span> distribution and the observed <span class="math inline">\(t\)</span> statistic. Ensure to use to highlight the rejection region and the <span class="math inline">\(p\)</span>-value. Additionally, add the resampling distribution for <span class="math inline">\(T\)</span> to the chart to demonstrate any differences between the null distribution and the distribution suggested by the data.</p>
<p><strong>Solution</strong></p>
<p><strong><em>For the farther values:</em></strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb33-2"><a href="#cb33-2"></a></span>
<span id="cb33-3"><a href="#cb33-3"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">12</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb33-6"><a href="#cb33-6"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb33-7"><a href="#cb33-7"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)  <span class="co"># centered at observed t</span></span>
<span id="cb33-8"><a href="#cb33-8"></a></span>
<span id="cb33-9"><a href="#cb33-9"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb33-10"><a href="#cb33-10"></a></span>
<span id="cb33-11"><a href="#cb33-11"></a>resample_t <span class="ot">&lt;-</span> (resample <span class="sc">-</span> <span class="fu">mean</span>(dat.kasdin<span class="sc">$</span>Farther.vals)) <span class="sc">/</span> </span>
<span id="cb33-12"><a href="#cb33-12"></a>              (<span class="fu">sd</span>(dat.kasdin<span class="sc">$</span>Farther.vals) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb33-13"><a href="#cb33-13"></a></span>
<span id="cb33-14"><a href="#cb33-14"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17"></a>  <span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(resample_t),</span>
<span id="cb33-18"><a href="#cb33-18"></a>                 <span class="fu">aes</span>(<span class="at">x =</span> resample_t, <span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb33-19"><a href="#cb33-19"></a>                 <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>, <span class="at">bins =</span> <span class="dv">6</span>,</span>
<span id="cb33-20"><a href="#cb33-20"></a>                 <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-histweird" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-histweird-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: t-distributions for the farther values and the resampling distribution
</figcaption>
<div aria-describedby="fig-histweird-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-histweird-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Here, we see the null t-distribution, the t-distribution shifted to be centered at our observed t-statistic, and the histogram of our resampling distribution standardized to be on the t-scale. I realize that I may have interpreted the earlier instructions for resampling wrong, and maybe it was suppoed to be bootstrapping, but I had guidance from Professor Cipolli during lab that suggested that this was correct. This histogram-scaling approach might be the correct answer, but it also isn’t something I’ve seen before. I am including it here because I am not sure exactly why it would be incorrect (if it is incorrect), and I look forward to getting feedback!</p>
<p>Also, the graph with bootstrapping:</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb34-2"><a href="#cb34-2"></a></span>
<span id="cb34-3"><a href="#cb34-3"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb34-4"><a href="#cb34-4"></a></span>
<span id="cb34-5"><a href="#cb34-5"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">12</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb34-6"><a href="#cb34-6"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb34-7"><a href="#cb34-7"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)  <span class="co"># centered at observed t</span></span>
<span id="cb34-8"><a href="#cb34-8"></a></span>
<span id="cb34-9"><a href="#cb34-9"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb34-10"><a href="#cb34-10"></a></span>
<span id="cb34-11"><a href="#cb34-11"></a>boot_t_far <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb34-12"><a href="#cb34-12"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-13"><a href="#cb34-13"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb34-14"><a href="#cb34-14"></a>})</span>
<span id="cb34-15"><a href="#cb34-15"></a></span>
<span id="cb34-16"><a href="#cb34-16"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb34-17"><a href="#cb34-17"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb34-18"><a href="#cb34-18"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb34-19"><a href="#cb34-19"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_far),</span>
<span id="cb34-20"><a href="#cb34-20"></a>             <span class="fu">aes</span>(<span class="at">x =</span> boot_t_far),</span>
<span id="cb34-21"><a href="#cb34-21"></a>             <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-22"><a href="#cb34-22"></a>             <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-farther1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-farther1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: t-distributions for the farther values
</figcaption>
<div aria-describedby="fig-farther1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-farther1-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>With both visualizations, the t-distribution actually appears to be an okay fit for the data. The data are a little more left-skewed, but it’s not horrible.</p>
<p><strong><em>For the closer values:</em></strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb35-2"><a href="#cb35-2"></a></span>
<span id="cb35-3"><a href="#cb35-3"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb35-4"><a href="#cb35-4"></a></span>
<span id="cb35-5"><a href="#cb35-5"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb35-6"><a href="#cb35-6"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb35-7"><a href="#cb35-7"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb35-8"><a href="#cb35-8"></a></span>
<span id="cb35-9"><a href="#cb35-9"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb35-10"><a href="#cb35-10"></a></span>
<span id="cb35-11"><a href="#cb35-11"></a>boot_t_close <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb35-12"><a href="#cb35-12"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-13"><a href="#cb35-13"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb35-14"><a href="#cb35-14"></a>})</span>
<span id="cb35-15"><a href="#cb35-15"></a></span>
<span id="cb35-16"><a href="#cb35-16"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb35-17"><a href="#cb35-17"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb35-18"><a href="#cb35-18"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb35-19"><a href="#cb35-19"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_close),</span>
<span id="cb35-20"><a href="#cb35-20"></a>               <span class="fu">aes</span>(<span class="at">x =</span> boot_t_close),</span>
<span id="cb35-21"><a href="#cb35-21"></a>               <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb35-22"><a href="#cb35-22"></a>               <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-closer1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-closer1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: t-distributions for the closer values
</figcaption>
<div aria-describedby="fig-closer1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-closer1-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Again, for the closer values, the t-distribution actually appears to be an okay fit for the data. The data are a little more right-skewed, but it’s not horrible.</p>
<p><strong><em>For the differences:</em></strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb36-2"><a href="#cb36-2"></a></span>
<span id="cb36-3"><a href="#cb36-3"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb36-4"><a href="#cb36-4"></a></span>
<span id="cb36-5"><a href="#cb36-5"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb36-6"><a href="#cb36-6"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb36-7"><a href="#cb36-7"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb36-8"><a href="#cb36-8"></a></span>
<span id="cb36-9"><a href="#cb36-9"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb36-10"><a href="#cb36-10"></a></span>
<span id="cb36-11"><a href="#cb36-11"></a>boot_t_diff <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb36-12"><a href="#cb36-12"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-13"><a href="#cb36-13"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb36-14"><a href="#cb36-14"></a>})</span>
<span id="cb36-15"><a href="#cb36-15"></a></span>
<span id="cb36-16"><a href="#cb36-16"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb36-17"><a href="#cb36-17"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb36-18"><a href="#cb36-18"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb36-19"><a href="#cb36-19"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_diff),</span>
<span id="cb36-20"><a href="#cb36-20"></a>               <span class="fu">aes</span>(<span class="at">x =</span> boot_t_diff),</span>
<span id="cb36-21"><a href="#cb36-21"></a>               <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-22"><a href="#cb36-22"></a>               <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-diff1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-diff1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: t-distributions for the differences
</figcaption>
<div aria-describedby="fig-diff1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lab13WriteUp_files/figure-html/fig-diff1-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p></p>
<p>Again, for the differences, the t-distribution actually appears to be an okay fit for the data. The data are a little more right-skewed, but it’s not horrible.</p>


<!-- -->


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-pwr" class="csl-entry" role="listitem">
Champely, Stephane. 2020. <em>Pwr: <span>B</span>asic Functions for Power Analysis</em>. <a href="https://CRAN.R-project.org/package=pwr">https://CRAN.R-project.org/package=pwr</a>.
</div>
<div id="ref-Kasdin25" class="csl-entry" role="listitem">
Kasdin, Jonathan, Alison Duffy, Nathan Nadler, Arnav Raha, Adrienne L Fairhall, Kimberly L Stachenfeld, and Vikram Gadagkar. 2025. <span>“Natural Behaviour Is Learned Through Dopamine-Mediated Reinforcement.”</span> <em>Nature</em>, 1–8.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb37-1"><a href="#cb37-1"></a><span class="co">---</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="an">title:</span><span class="co"> Lab Thirteen -- Statistical Inference # Title of the document</span></span>
<span id="cb37-3"><a href="#cb37-3"></a></span>
<span id="cb37-4"><a href="#cb37-4"></a><span class="co"># Bibliography Details</span></span>
<span id="cb37-5"><a href="#cb37-5"></a><span class="an">bibliography:</span><span class="co"> Lab13References.bib  # Name of bib file in the same folder </span></span>
<span id="cb37-6"><a href="#cb37-6"></a><span class="an">bibliographystyle:</span><span class="co"> apa            # Bibliography style</span></span>
<span id="cb37-7"><a href="#cb37-7"></a></span>
<span id="cb37-8"><a href="#cb37-8"></a><span class="an">execute:</span><span class="co">               # Default settings for code blocks</span></span>
<span id="cb37-9"><a href="#cb37-9"></a><span class="co">  warning: false       # Do not print warnings</span></span>
<span id="cb37-10"><a href="#cb37-10"></a><span class="co">  message: false       # Do not print messages</span></span>
<span id="cb37-11"><a href="#cb37-11"></a><span class="co">  size: "scriptsize"   # Set code size to script size</span></span>
<span id="cb37-12"><a href="#cb37-12"></a></span>
<span id="cb37-13"><a href="#cb37-13"></a><span class="co"># Below will do html by default. To render the entire project</span></span>
<span id="cb37-14"><a href="#cb37-14"></a><span class="co"># Use the following code:</span></span>
<span id="cb37-15"><a href="#cb37-15"></a><span class="co"># quarto::quarto_render("Lab10WriteUp.qmd")</span></span>
<span id="cb37-16"><a href="#cb37-16"></a><span class="an">format:</span></span>
<span id="cb37-17"><a href="#cb37-17"></a><span class="co">  pdf:        # Specify .pdf formatting options </span></span>
<span id="cb37-18"><a href="#cb37-18"></a><span class="co">    documentclass: article     # Document Class</span></span>
<span id="cb37-19"><a href="#cb37-19"></a><span class="co">    number-sections: true      # Number Sections</span></span>
<span id="cb37-20"><a href="#cb37-20"></a><span class="co">    reference-section-title: "References" # Title for reference section</span></span>
<span id="cb37-21"><a href="#cb37-21"></a><span class="co">    code-line-numbers: true    # Line numbers printed in code</span></span>
<span id="cb37-22"><a href="#cb37-22"></a><span class="co">    cap-location: top          # Captions at the top of tables </span></span>
<span id="cb37-23"><a href="#cb37-23"></a><span class="co">    geometry:</span></span>
<span id="cb37-24"><a href="#cb37-24"></a><span class="co">      - top=0.75in</span></span>
<span id="cb37-25"><a href="#cb37-25"></a><span class="co">      - left=0.75in</span></span>
<span id="cb37-26"><a href="#cb37-26"></a><span class="co">      - bottom=0.75in</span></span>
<span id="cb37-27"><a href="#cb37-27"></a><span class="co">      - right=0.75in</span></span>
<span id="cb37-28"><a href="#cb37-28"></a><span class="co">  html:       # Specify HTML formatting options </span></span>
<span id="cb37-29"><a href="#cb37-29"></a><span class="co">    number-sections: true      # Number Sections</span></span>
<span id="cb37-30"><a href="#cb37-30"></a><span class="co">    code-fold: true            # Button to show code</span></span>
<span id="cb37-31"><a href="#cb37-31"></a><span class="co">    code-line-numbers: true    # Line numbers printed in code</span></span>
<span id="cb37-32"><a href="#cb37-32"></a><span class="co">    cap-location: top          # Captions at the top of tables and figures</span></span>
<span id="cb37-33"><a href="#cb37-33"></a><span class="an">format-links:</span><span class="co"> [pdf]</span></span>
<span id="cb37-34"><a href="#cb37-34"></a><span class="co">---</span></span>
<span id="cb37-35"><a href="#cb37-35"></a></span>
<span id="cb37-38"><a href="#cb37-38"></a><span class="in">```{r}</span></span>
<span id="cb37-39"><a href="#cb37-39"></a><span class="co">#| echo: false</span></span>
<span id="cb37-40"><a href="#cb37-40"></a></span>
<span id="cb37-41"><a href="#cb37-41"></a>default_chunk_hook  <span class="ot">&lt;-</span> knitr<span class="sc">::</span>knit_hooks<span class="sc">$</span><span class="fu">get</span>(<span class="st">"chunk"</span>)</span>
<span id="cb37-42"><a href="#cb37-42"></a></span>
<span id="cb37-43"><a href="#cb37-43"></a>latex_font_size <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Huge"</span>, <span class="st">"huge"</span>, <span class="st">"LARGE"</span>, <span class="st">"Large"</span>, </span>
<span id="cb37-44"><a href="#cb37-44"></a>                     <span class="st">"large"</span>, <span class="st">"normalsize"</span>, <span class="st">"small"</span>, </span>
<span id="cb37-45"><a href="#cb37-45"></a>                     <span class="st">"footnotesize"</span>, <span class="st">"scriptsize"</span>, <span class="st">"tiny"</span>)</span>
<span id="cb37-46"><a href="#cb37-46"></a></span>
<span id="cb37-47"><a href="#cb37-47"></a>knitr<span class="sc">::</span>knit_hooks<span class="sc">$</span><span class="fu">set</span>(<span class="at">chunk =</span> <span class="cf">function</span>(x, options) {</span>
<span id="cb37-48"><a href="#cb37-48"></a>  x <span class="ot">&lt;-</span> <span class="fu">default_chunk_hook</span>(x, options)</span>
<span id="cb37-49"><a href="#cb37-49"></a>  <span class="cf">if</span>(options<span class="sc">$</span>size <span class="sc">%in%</span> latex_font_size) {</span>
<span id="cb37-50"><a href="#cb37-50"></a>    <span class="fu">paste0</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> </span><span class="sc">\\</span><span class="st">"</span>, options<span class="sc">$</span>size, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>, </span>
<span id="cb37-51"><a href="#cb37-51"></a>      x, </span>
<span id="cb37-52"><a href="#cb37-52"></a>      <span class="st">"</span><span class="sc">\n\n</span><span class="st"> </span><span class="sc">\\</span><span class="st">normalsize"</span></span>
<span id="cb37-53"><a href="#cb37-53"></a>    )</span>
<span id="cb37-54"><a href="#cb37-54"></a>  } <span class="cf">else</span> {</span>
<span id="cb37-55"><a href="#cb37-55"></a>    x</span>
<span id="cb37-56"><a href="#cb37-56"></a>  }</span>
<span id="cb37-57"><a href="#cb37-57"></a>})</span>
<span id="cb37-58"><a href="#cb37-58"></a><span class="in">```</span></span>
<span id="cb37-59"><a href="#cb37-59"></a></span>
<span id="cb37-62"><a href="#cb37-62"></a><span class="in">```{r}</span></span>
<span id="cb37-63"><a href="#cb37-63"></a><span class="co">#| label: load-packages</span></span>
<span id="cb37-64"><a href="#cb37-64"></a><span class="co">#| include: false</span></span>
<span id="cb37-65"><a href="#cb37-65"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb37-66"><a href="#cb37-66"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb37-67"><a href="#cb37-67"></a><span class="in">```</span></span>
<span id="cb37-68"><a href="#cb37-68"></a></span>
<span id="cb37-69"><a href="#cb37-69"></a><span class="fu"># Remaining Portfolio Work!</span></span>
<span id="cb37-70"><a href="#cb37-70"></a></span>
<span id="cb37-71"><a href="#cb37-71"></a>**By 5p 4/27** Email me a link to your GitHub page with all polished labs rendered, and your review material (at least one unit). In the email, you should include a reflection about the processes involved in creating this portfolio and what you learned as a result. If you're having trouble reflecting, consider Fink's Taxonomy of Significant Learning (Google Fink taxonomy aligned self-reflection questions). In the email, let me know whether you would be comfortable sharing your page -- I'm hoping that together we can get a good study guide for the final.</span>
<span id="cb37-72"><a href="#cb37-72"></a></span>
<span id="cb37-73"><a href="#cb37-73"></a><span class="fu"># Statistical Inference</span></span>
<span id="cb37-74"><a href="#cb37-74"></a></span>
<span id="cb37-75"><a href="#cb37-75"></a>@Kasdin25 show that dopamine in the brains of young zebra finches acts as </span>
<span id="cb37-76"><a href="#cb37-76"></a>a learning signal, increasing when they sing closer to their adult song and </span>
<span id="cb37-77"><a href="#cb37-77"></a>decreasing when they sing further away, effectively guiding their vocal </span>
<span id="cb37-78"><a href="#cb37-78"></a>development through trial-and-error. This suggests that complex natural </span>
<span id="cb37-79"><a href="#cb37-79"></a>behaviors, like learning to sing, are shaped by dopamine-driven reinforcement </span>
<span id="cb37-80"><a href="#cb37-80"></a>learning, similar to how artificial intelligence learns. You can find the </span>
<span id="cb37-81"><a href="#cb37-81"></a>paper at this link: <span class="co">[</span><span class="ot">https://www.nature.com/articles/s41586-025-08729-1</span><span class="co">](https://www.nature.com/articles/s41586-025-08729-1)</span>.</span>
<span id="cb37-82"><a href="#cb37-82"></a></span>
<span id="cb37-83"><a href="#cb37-83"></a>Note that the measurement is rather complicated. First, the measurements are taken on syllables of a bird song. When discussing bird songs, the term syllable refers to a single, distinct, uninterrupted sound that is part of a</span>
<span id="cb37-84"><a href="#cb37-84"></a>possibly complex bird song.</span>
<span id="cb37-85"><a href="#cb37-85"></a></span>
<span id="cb37-86"><a href="#cb37-86"></a>They initially describe their measurement as follows. They compare the sound of the developing zebra finches to the median sound of adult zebra finches, that act as a "goal" sound.</span>
<span id="cb37-87"><a href="#cb37-87"></a>\begin{quote}</span>
<span id="cb37-88"><a href="#cb37-88"></a>"For each syllable rendition, we calculated the proximity (Euclidean distance) to the median of the adult renditions of the syllable (age $&gt;$ 90 days) in feature space (Fig. 2a,b)."</span>
<span id="cb37-89"><a href="#cb37-89"></a>\end{quote}</span>
<span id="cb37-90"><a href="#cb37-90"></a></span>
<span id="cb37-91"><a href="#cb37-91"></a>They contextualize that measurement by computing a "relative quality" that takes into account their current ability (e.g., are they getting closer or further compared to their previous 14 renditions).</span>
<span id="cb37-92"><a href="#cb37-92"></a>\begin{quote}</span>
<span id="cb37-93"><a href="#cb37-93"></a>"Because dopamine is hypothesized to encode the relative value of performance, we defined the 'relative quality' of a syllable as proximity to the adult version of the syllable relative to the mean of the previous 14 renditions (Methods)."</span>
<span id="cb37-94"><a href="#cb37-94"></a>\end{quote}</span>
<span id="cb37-95"><a href="#cb37-95"></a></span>
<span id="cb37-96"><a href="#cb37-96"></a>They define the "closer" measurements as the 10% of syllable renditions with the highest relative quality and the "further" as the lowest 10%.</span>
<span id="cb37-97"><a href="#cb37-97"></a>\begin{quote}</span>
<span id="cb37-98"><a href="#cb37-98"></a>"To test for online error responses, for each day we compared the dopamine activity associated with the 10% of syllable renditions with the highest relative quality with that of the 10% of renditions with the lowest relative quality (Fig. 2c–g)."</span>
<span id="cb37-99"><a href="#cb37-99"></a>\end{quote}</span>
<span id="cb37-100"><a href="#cb37-100"></a></span>
<span id="cb37-101"><a href="#cb37-101"></a>Note that the data are measures of dopamine change, they use fibre photometry, changes in the fluorescence indicate dopamine changes in realtime. Their specific measurement considers the percent change in flourescence in 100-ms windows between 200 and 300 ms from the start of singing, averaged across development.</span>
<span id="cb37-102"><a href="#cb37-102"></a></span>
<span id="cb37-103"><a href="#cb37-103"></a>Finally, the researchers note that they adjust the observations to correct for the increased dopamine for singing at all (whether it is close or far).</span>
<span id="cb37-104"><a href="#cb37-104"></a>\begin{quote}</span>
<span id="cb37-105"><a href="#cb37-105"></a>"As previously reported, the baseline level of dopamine in Area X is known to increase during singing; to isolate the effect of syllable quality from these singing-related dopamine increases, we subtracted the mean dopamine response across all renditions of a syllable on each day from the dopamine response for each rendition."</span>
<span id="cb37-106"><a href="#cb37-106"></a>\end{quote}</span>
<span id="cb37-107"><a href="#cb37-107"></a></span>
<span id="cb37-108"><a href="#cb37-108"></a>So, the random variables we are working with are:</span>
<span id="cb37-109"><a href="#cb37-109"></a>\begin{align*}</span>
<span id="cb37-110"><a href="#cb37-110"></a>X_{\text{close}} &amp;= \text{average \% change in fluorescence for the top 10\% syllable renditions} <span class="sc">\\</span></span>
<span id="cb37-111"><a href="#cb37-111"></a>&amp;\quad \text{relative to distance from adult sound (corrected for singing)} <span class="sc">\\</span><span class="co">[</span><span class="ot">1ex</span><span class="co">]</span></span>
<span id="cb37-112"><a href="#cb37-112"></a>X_{\text{far}} &amp;= \text{average \% change in fluorescence for the bottom 10\% syllable renditions} <span class="sc">\\</span></span>
<span id="cb37-113"><a href="#cb37-113"></a>&amp;\quad \text{relative to distance from adult sound (corrected for singing)}</span>
<span id="cb37-114"><a href="#cb37-114"></a>\end{align*}</span>
<span id="cb37-115"><a href="#cb37-115"></a></span>
<span id="cb37-116"><a href="#cb37-116"></a>That is, the unit of measure is the syllable as measured on six birds, and the measurement is somewhat complicated.</span>
<span id="cb37-117"><a href="#cb37-117"></a></span>
<span id="cb37-118"><a href="#cb37-118"></a><span class="fu">## Part a</span></span>
<span id="cb37-119"><a href="#cb37-119"></a>Using the <span class="in">`pwr`</span> package for \texttt{R} <span class="co">[</span><span class="ot">@pwr</span><span class="co">]</span>, conduct a power analysis. How many observations would the researchers need to detect a moderate-to-large effect ($d=0.65$) when using $\alpha=0.05$ and default power (0.80) for a two-sided one sample $t$ test.</span>
<span id="cb37-120"><a href="#cb37-120"></a></span>
<span id="cb37-121"><a href="#cb37-121"></a>**Solution**</span>
<span id="cb37-122"><a href="#cb37-122"></a></span>
<span id="cb37-125"><a href="#cb37-125"></a><span class="in">```{r}</span></span>
<span id="cb37-126"><a href="#cb37-126"></a><span class="co">#| include: false</span></span>
<span id="cb37-127"><a href="#cb37-127"></a><span class="fu">library</span>(pwr)</span>
<span id="cb37-128"><a href="#cb37-128"></a><span class="in">```</span></span>
<span id="cb37-129"><a href="#cb37-129"></a></span>
<span id="cb37-132"><a href="#cb37-132"></a><span class="in">```{r}</span></span>
<span id="cb37-133"><a href="#cb37-133"></a>(<span class="at">power =</span> <span class="fu">pwr.t.test</span>(</span>
<span id="cb37-134"><a href="#cb37-134"></a>  <span class="at">n =</span> <span class="cn">NULL</span>, <span class="at">d =</span> <span class="fl">0.65</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>, </span>
<span id="cb37-135"><a href="#cb37-135"></a>  <span class="at">type =</span> <span class="st">"one.sample"</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>))</span>
<span id="cb37-136"><a href="#cb37-136"></a></span>
<span id="cb37-137"><a href="#cb37-137"></a><span class="co"># graph if i have time</span></span>
<span id="cb37-138"><a href="#cb37-138"></a></span>
<span id="cb37-139"><a href="#cb37-139"></a><span class="in">```</span></span>
<span id="cb37-140"><a href="#cb37-140"></a></span>
<span id="cb37-141"><a href="#cb37-141"></a>The researchers should have at least 21 observations.</span>
<span id="cb37-142"><a href="#cb37-142"></a></span>
<span id="cb37-143"><a href="#cb37-143"></a><span class="fu">## Part b</span></span>
<span id="cb37-144"><a href="#cb37-144"></a>Click the link to go to the paper. Find the source data for Figure 2. Download the Excel file. Describe what you needed to do to collect the data for Figure 2(g). Note that you only need the <span class="in">`closer_vals`</span> and <span class="in">`further_vals`</span>. Ensure to <span class="in">`mutate()`</span> the data to get a difference (e.g., <span class="in">`closer_vals - further_vals`</span>).</span>
<span id="cb37-145"><a href="#cb37-145"></a></span>
<span id="cb37-146"><a href="#cb37-146"></a>**Solution**</span>
<span id="cb37-147"><a href="#cb37-147"></a></span>
<span id="cb37-148"><a href="#cb37-148"></a>To get the data for Figure 2(g), I downloaded the source data into an unweildly and very large Excel file. Only a small subset of these data were needed. I copied the <span class="in">`closer.vals`</span> data to the <span class="in">`further.vals`</span> sheet, and then exported that sheet to this lab in my Mac files. Now, I have the data locally and it will be easy to keep track of in the future. </span>
<span id="cb37-149"><a href="#cb37-149"></a></span>
<span id="cb37-152"><a href="#cb37-152"></a><span class="in">```{r}</span></span>
<span id="cb37-153"><a href="#cb37-153"></a>dat.kasdin <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"CompStatLab13Data.csv"</span>)</span>
<span id="cb37-154"><a href="#cb37-154"></a><span class="fu">head</span>(dat.kasdin)</span>
<span id="cb37-155"><a href="#cb37-155"></a><span class="in">```</span></span>
<span id="cb37-156"><a href="#cb37-156"></a></span>
<span id="cb37-157"><a href="#cb37-157"></a><span class="fu">## Part c</span></span>
<span id="cb37-158"><a href="#cb37-158"></a>Summarize the data.</span>
<span id="cb37-159"><a href="#cb37-159"></a></span>
<span id="cb37-160"><a href="#cb37-160"></a><span class="ss">* </span>Summarize the further data. Do the data suggest that dopamine in the brains of young zebra finches decreases when they sing further away?</span>
<span id="cb37-161"><a href="#cb37-161"></a><span class="ss">* </span>Summarize the closer data. Do the data suggest that dopamine in the brains of young zebra finches increases when they sing closer to their adult song?</span>
<span id="cb37-162"><a href="#cb37-162"></a><span class="ss">* </span>Summarize the paired differences. Do the data suggest that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song?</span>
<span id="cb37-163"><a href="#cb37-163"></a><span class="ss">* </span>**Optional Challenge** Can you reproduce Figure 2(g)? Note that the you can use \texttt{geom<span class="sc">\_</span>errorbar()} to plot the range created by adding the mean $\pm$ one standard deviation.</span>
<span id="cb37-164"><a href="#cb37-164"></a></span>
<span id="cb37-165"><a href="#cb37-165"></a>**Solution**</span>
<span id="cb37-166"><a href="#cb37-166"></a></span>
<span id="cb37-169"><a href="#cb37-169"></a><span class="in">```{r}</span></span>
<span id="cb37-170"><a href="#cb37-170"></a><span class="co">#| label: fig-farther</span></span>
<span id="cb37-171"><a href="#cb37-171"></a><span class="co">#| fig-cap: Histogram of Farther Values</span></span>
<span id="cb37-172"><a href="#cb37-172"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-173"><a href="#cb37-173"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Farther.vals)) <span class="sc">+</span></span>
<span id="cb37-174"><a href="#cb37-174"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.8</span>, <span class="fl">0.1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb37-175"><a href="#cb37-175"></a>plot</span>
<span id="cb37-176"><a href="#cb37-176"></a><span class="in">```</span></span>
<span id="cb37-177"><a href="#cb37-177"></a></span>
<span id="cb37-178"><a href="#cb37-178"></a></span>
<span id="cb37-181"><a href="#cb37-181"></a><span class="in">```{r}</span></span>
<span id="cb37-182"><a href="#cb37-182"></a><span class="co">#| label: tbl-farther.summary</span></span>
<span id="cb37-183"><a href="#cb37-183"></a><span class="co">#| tbl-cap: Summary of the Farther Values </span></span>
<span id="cb37-184"><a href="#cb37-184"></a></span>
<span id="cb37-185"><a href="#cb37-185"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-186"><a href="#cb37-186"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-187"><a href="#cb37-187"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Farther.vals),</span>
<span id="cb37-188"><a href="#cb37-188"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Farther.vals),</span>
<span id="cb37-189"><a href="#cb37-189"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Farther.vals),</span>
<span id="cb37-190"><a href="#cb37-190"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Farther.vals)</span>
<span id="cb37-191"><a href="#cb37-191"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb37-192"><a href="#cb37-192"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb37-193"><a href="#cb37-193"></a>summary</span>
<span id="cb37-194"><a href="#cb37-194"></a><span class="in">```</span></span>
<span id="cb37-195"><a href="#cb37-195"></a></span>
<span id="cb37-196"><a href="#cb37-196"></a>We have preliminary evidence that supports the conjecture that dopamine in the brains of young zebra finches decreases when they sing further away from their adult song- our mean and median are below zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram shows an approximately left-skewed distribution, with some values near zero.</span>
<span id="cb37-197"><a href="#cb37-197"></a></span>
<span id="cb37-198"><a href="#cb37-198"></a></span>
<span id="cb37-201"><a href="#cb37-201"></a><span class="in">```{r}</span></span>
<span id="cb37-202"><a href="#cb37-202"></a><span class="co">#| label: fig-closer</span></span>
<span id="cb37-203"><a href="#cb37-203"></a><span class="co">#| fig-cap: Histogram of Closer Values</span></span>
<span id="cb37-204"><a href="#cb37-204"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-205"><a href="#cb37-205"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Closer.vals)) <span class="sc">+</span></span>
<span id="cb37-206"><a href="#cb37-206"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb37-207"><a href="#cb37-207"></a>plot</span>
<span id="cb37-208"><a href="#cb37-208"></a><span class="in">```</span></span>
<span id="cb37-209"><a href="#cb37-209"></a></span>
<span id="cb37-212"><a href="#cb37-212"></a><span class="in">```{r}</span></span>
<span id="cb37-213"><a href="#cb37-213"></a><span class="co">#| label: tbl-closer.summary</span></span>
<span id="cb37-214"><a href="#cb37-214"></a><span class="co">#| tbl-cap: Summary of the Closer Values </span></span>
<span id="cb37-215"><a href="#cb37-215"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-216"><a href="#cb37-216"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-217"><a href="#cb37-217"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Closer.vals),</span>
<span id="cb37-218"><a href="#cb37-218"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Closer.vals),</span>
<span id="cb37-219"><a href="#cb37-219"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Closer.vals),</span>
<span id="cb37-220"><a href="#cb37-220"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Closer.vals)</span>
<span id="cb37-221"><a href="#cb37-221"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb37-222"><a href="#cb37-222"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb37-223"><a href="#cb37-223"></a>summary</span>
<span id="cb37-224"><a href="#cb37-224"></a><span class="in">```</span></span>
<span id="cb37-225"><a href="#cb37-225"></a></span>
<span id="cb37-226"><a href="#cb37-226"></a>We have preliminary evidence that supports the conjecture that dopamine in the brains of young zebra finches increases when they sing closer to their adult song- our mean and median are above zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram show some values near zero, with an approximately symmetric distrivution. </span>
<span id="cb37-227"><a href="#cb37-227"></a></span>
<span id="cb37-230"><a href="#cb37-230"></a><span class="in">```{r}</span></span>
<span id="cb37-231"><a href="#cb37-231"></a>dat.kasdin <span class="ot">=</span>  dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-232"><a href="#cb37-232"></a>  <span class="fu">mutate</span>(<span class="at">Difference =</span> Closer.vals<span class="sc">-</span>Farther.vals)</span>
<span id="cb37-233"><a href="#cb37-233"></a><span class="in">```</span></span>
<span id="cb37-234"><a href="#cb37-234"></a></span>
<span id="cb37-237"><a href="#cb37-237"></a><span class="in">```{r}</span></span>
<span id="cb37-238"><a href="#cb37-238"></a><span class="co">#| label: fig-diff</span></span>
<span id="cb37-239"><a href="#cb37-239"></a><span class="co">#| fig-cap: Histogram of Differences</span></span>
<span id="cb37-240"><a href="#cb37-240"></a>plot <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-241"><a href="#cb37-241"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Difference)) <span class="sc">+</span></span>
<span id="cb37-242"><a href="#cb37-242"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">1.1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb37-243"><a href="#cb37-243"></a>plot</span>
<span id="cb37-244"><a href="#cb37-244"></a><span class="in">```</span></span>
<span id="cb37-245"><a href="#cb37-245"></a></span>
<span id="cb37-246"><a href="#cb37-246"></a></span>
<span id="cb37-249"><a href="#cb37-249"></a><span class="in">```{r}</span></span>
<span id="cb37-250"><a href="#cb37-250"></a><span class="co">#| label: tbl-differences.summary</span></span>
<span id="cb37-251"><a href="#cb37-251"></a><span class="co">#| tbl-cap: Summary of the Paired Differences </span></span>
<span id="cb37-252"><a href="#cb37-252"></a>summary <span class="ot">=</span> dat.kasdin <span class="sc">|&gt;</span></span>
<span id="cb37-253"><a href="#cb37-253"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-254"><a href="#cb37-254"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(Difference),</span>
<span id="cb37-255"><a href="#cb37-255"></a>    <span class="at">Median =</span> <span class="fu">median</span>(Difference),</span>
<span id="cb37-256"><a href="#cb37-256"></a>    <span class="st">'Standard Deviation'</span> <span class="ot">=</span> <span class="fu">sd</span>(Difference),</span>
<span id="cb37-257"><a href="#cb37-257"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(Difference)</span>
<span id="cb37-258"><a href="#cb37-258"></a>  )<span class="sc">|&gt;</span></span>
<span id="cb37-259"><a href="#cb37-259"></a>knitr<span class="sc">::</span><span class="fu">kable</span>()</span>
<span id="cb37-260"><a href="#cb37-260"></a>summary</span>
<span id="cb37-261"><a href="#cb37-261"></a><span class="in">```</span></span>
<span id="cb37-262"><a href="#cb37-262"></a></span>
<span id="cb37-263"><a href="#cb37-263"></a>We have preliminary evidence that supports the conjecture that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song- our mean and median are above zero, and our standard deviation is less than the distance from zero of both the mean and median. The variance is very small. The histogram shows an approximately uniform distribution, with one slight outlier.</span>
<span id="cb37-264"><a href="#cb37-264"></a></span>
<span id="cb37-265"><a href="#cb37-265"></a><span class="fu">## Part d</span></span>
<span id="cb37-266"><a href="#cb37-266"></a>Conduct the inferences they do in the paper. Make sure to report the results a little more comprehensively -- that is your parenthetical should look something like: ($t=23.99$, $p&lt;0.0001$; $g=1.34$; 95% CI: 4.43, 4.60). Ensure to verify any conditions for use.\</span>
<span id="cb37-267"><a href="#cb37-267"></a>**Note**: Your numbers will vary slightly because they reported two-sided test $p$-values instead of the specified one-sided tests. </span>
<span id="cb37-268"><a href="#cb37-268"></a></span>
<span id="cb37-269"><a href="#cb37-269"></a><span class="ss">* </span>"The close responses differed significantly from 0 ($p=1.63 \times 10^{-8}$).''\</span>
<span id="cb37-270"><a href="#cb37-270"></a>**Note**: Use the appropriate one-sided test.</span>
<span id="cb37-271"><a href="#cb37-271"></a><span class="ss">* </span>"The far responses differed significantly from 0 ($p=5.17 \times 10^{-8}$).''\</span>
<span id="cb37-272"><a href="#cb37-272"></a>**Note**: Use the appropriate one-sided test.</span>
<span id="cb37-273"><a href="#cb37-273"></a><span class="ss">* </span>"The difference between populations was significant ($p=1.04 \times10^{-8}$).''\</span>
<span id="cb37-274"><a href="#cb37-274"></a>**Note**: Use the two-sided test.</span>
<span id="cb37-275"><a href="#cb37-275"></a></span>
<span id="cb37-276"><a href="#cb37-276"></a>**Solution**</span>
<span id="cb37-277"><a href="#cb37-277"></a></span>
<span id="cb37-278"><a href="#cb37-278"></a>For the closer values: we have a sample size of 25 and our data are approximately left-skewed. We really don't fit the conditions for use, but we are close and it will be good practice, so we will proceed!</span>
<span id="cb37-279"><a href="#cb37-279"></a></span>
<span id="cb37-282"><a href="#cb37-282"></a><span class="in">```{r}</span></span>
<span id="cb37-283"><a href="#cb37-283"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb37-284"><a href="#cb37-284"></a></span>
<span id="cb37-285"><a href="#cb37-285"></a><span class="co"># t-test:</span></span>
<span id="cb37-286"><a href="#cb37-286"></a></span>
<span id="cb37-287"><a href="#cb37-287"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span>
<span id="cb37-288"><a href="#cb37-288"></a></span>
<span id="cb37-289"><a href="#cb37-289"></a><span class="co"># effect size:</span></span>
<span id="cb37-290"><a href="#cb37-290"></a></span>
<span id="cb37-291"><a href="#cb37-291"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span>
<span id="cb37-292"><a href="#cb37-292"></a></span>
<span id="cb37-293"><a href="#cb37-293"></a><span class="co"># get confidence interval: </span></span>
<span id="cb37-294"><a href="#cb37-294"></a></span>
<span id="cb37-295"><a href="#cb37-295"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span>
<span id="cb37-296"><a href="#cb37-296"></a></span>
<span id="cb37-297"><a href="#cb37-297"></a><span class="in">```</span> </span>
<span id="cb37-298"><a href="#cb37-298"></a></span>
<span id="cb37-299"><a href="#cb37-299"></a>We do have statistically discernible support for the hypothesis that dopamine in the brains of young zebra finches increases when they sing closer to their adult song ($t=9.16, p&lt;0.05, g=1.77, 95 \% \hspace{0.15cm} CI : (0.139,0.22)$).</span>
<span id="cb37-300"><a href="#cb37-300"></a></span>
<span id="cb37-301"><a href="#cb37-301"></a>Now, let's check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</span>
<span id="cb37-302"><a href="#cb37-302"></a></span>
<span id="cb37-305"><a href="#cb37-305"></a><span class="in">```{r}</span></span>
<span id="cb37-306"><a href="#cb37-306"></a><span class="co">#| label: fig-closer2</span></span>
<span id="cb37-307"><a href="#cb37-307"></a><span class="co">#| fig-cap: histogram of the closer resampling values</span></span>
<span id="cb37-308"><a href="#cb37-308"></a></span>
<span id="cb37-309"><a href="#cb37-309"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-310"><a href="#cb37-310"></a></span>
<span id="cb37-311"><a href="#cb37-311"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb37-312"><a href="#cb37-312"></a></span>
<span id="cb37-313"><a href="#cb37-313"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb37-314"><a href="#cb37-314"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">4</span>)</span>
<span id="cb37-315"><a href="#cb37-315"></a></span>
<span id="cb37-316"><a href="#cb37-316"></a><span class="in">```</span></span>
<span id="cb37-317"><a href="#cb37-317"></a></span>
<span id="cb37-318"><a href="#cb37-318"></a>Our data are still skewed. The researchers really should not have done a t-test here, as the conditions for use are not met.</span>
<span id="cb37-319"><a href="#cb37-319"></a></span>
<span id="cb37-320"><a href="#cb37-320"></a></span>
<span id="cb37-321"><a href="#cb37-321"></a>For the further values: we have a sample size of 25 and our data are approximately symmetric. We have somewhat unsure footing, but we will proceed anyway! </span>
<span id="cb37-322"><a href="#cb37-322"></a></span>
<span id="cb37-325"><a href="#cb37-325"></a><span class="in">```{r}</span></span>
<span id="cb37-326"><a href="#cb37-326"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb37-327"><a href="#cb37-327"></a></span>
<span id="cb37-328"><a href="#cb37-328"></a><span class="co"># t-test:</span></span>
<span id="cb37-329"><a href="#cb37-329"></a></span>
<span id="cb37-330"><a href="#cb37-330"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span>
<span id="cb37-331"><a href="#cb37-331"></a></span>
<span id="cb37-332"><a href="#cb37-332"></a><span class="co"># effect size:</span></span>
<span id="cb37-333"><a href="#cb37-333"></a></span>
<span id="cb37-334"><a href="#cb37-334"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span>
<span id="cb37-335"><a href="#cb37-335"></a></span>
<span id="cb37-336"><a href="#cb37-336"></a><span class="co"># get confidence interval: </span></span>
<span id="cb37-337"><a href="#cb37-337"></a></span>
<span id="cb37-338"><a href="#cb37-338"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span>
<span id="cb37-339"><a href="#cb37-339"></a></span>
<span id="cb37-340"><a href="#cb37-340"></a><span class="in">```</span></span>
<span id="cb37-341"><a href="#cb37-341"></a></span>
<span id="cb37-342"><a href="#cb37-342"></a>We do have statistically discernible support for the hypothesis that dopamine in the brains of young zebra finches decreases when they sing further away from their adult song ($t=-7.92, p&lt;0.05, g=-1.53, 95 \% \hspace{0.15cm} CI : (-0.27,-0.16)$). </span>
<span id="cb37-343"><a href="#cb37-343"></a></span>
<span id="cb37-344"><a href="#cb37-344"></a></span>
<span id="cb37-345"><a href="#cb37-345"></a>Now, let's check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</span>
<span id="cb37-346"><a href="#cb37-346"></a></span>
<span id="cb37-349"><a href="#cb37-349"></a><span class="in">```{r}</span></span>
<span id="cb37-350"><a href="#cb37-350"></a><span class="co">#| label: fig-farther2</span></span>
<span id="cb37-351"><a href="#cb37-351"></a><span class="co">#| fig-cap: histogram of the farther resampling values</span></span>
<span id="cb37-352"><a href="#cb37-352"></a></span>
<span id="cb37-353"><a href="#cb37-353"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-354"><a href="#cb37-354"></a></span>
<span id="cb37-355"><a href="#cb37-355"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb37-356"><a href="#cb37-356"></a></span>
<span id="cb37-357"><a href="#cb37-357"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb37-358"><a href="#cb37-358"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">4</span>)</span>
<span id="cb37-359"><a href="#cb37-359"></a></span>
<span id="cb37-360"><a href="#cb37-360"></a><span class="in">```</span></span>
<span id="cb37-361"><a href="#cb37-361"></a></span>
<span id="cb37-362"><a href="#cb37-362"></a>Our data are still *very* skewed. The researchers really should not have done a t-test here, as the conditions for use are not met.</span>
<span id="cb37-363"><a href="#cb37-363"></a></span>
<span id="cb37-364"><a href="#cb37-364"></a></span>
<span id="cb37-365"><a href="#cb37-365"></a>For the differences: we have a sample size of 25 and our data are approximately symmetric. We have somewhat unsure footing, but we will proceed anyway! </span>
<span id="cb37-366"><a href="#cb37-366"></a></span>
<span id="cb37-369"><a href="#cb37-369"></a><span class="in">```{r}</span></span>
<span id="cb37-370"><a href="#cb37-370"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb37-371"><a href="#cb37-371"></a></span>
<span id="cb37-372"><a href="#cb37-372"></a><span class="co"># t-test:</span></span>
<span id="cb37-373"><a href="#cb37-373"></a></span>
<span id="cb37-374"><a href="#cb37-374"></a>(<span class="at">ttest =</span> <span class="fu">t.test</span>(<span class="at">x =</span> dat.kasdin<span class="sc">$</span>Difference, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span>
<span id="cb37-375"><a href="#cb37-375"></a></span>
<span id="cb37-376"><a href="#cb37-376"></a><span class="co"># effect size:</span></span>
<span id="cb37-377"><a href="#cb37-377"></a></span>
<span id="cb37-378"><a href="#cb37-378"></a><span class="fu">hedges_g</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">ci =</span> <span class="fl">0.95</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb37-379"><a href="#cb37-379"></a></span>
<span id="cb37-380"><a href="#cb37-380"></a><span class="co"># Note that we already have a valid confidence interval from our original t-test.</span></span>
<span id="cb37-381"><a href="#cb37-381"></a></span>
<span id="cb37-382"><a href="#cb37-382"></a><span class="in">```</span></span>
<span id="cb37-383"><a href="#cb37-383"></a></span>
<span id="cb37-384"><a href="#cb37-384"></a></span>
<span id="cb37-385"><a href="#cb37-385"></a>We do have statistically discernible support for the hypothesis that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song ($t=9.14, p&lt;0.05, g=1.77, 95 \% \hspace{0.15cm} CI : (0.303,0.480)$). </span>
<span id="cb37-386"><a href="#cb37-386"></a></span>
<span id="cb37-387"><a href="#cb37-387"></a>Now, let's check if we can still apply the central limit theorem, or if the data are too skewed. We will check using resampling!</span>
<span id="cb37-388"><a href="#cb37-388"></a></span>
<span id="cb37-391"><a href="#cb37-391"></a><span class="in">```{r}</span></span>
<span id="cb37-392"><a href="#cb37-392"></a><span class="co">#| label: fig-diff2</span></span>
<span id="cb37-393"><a href="#cb37-393"></a><span class="co">#| fig-cap: histogram of the resampling values for the differences </span></span>
<span id="cb37-394"><a href="#cb37-394"></a></span>
<span id="cb37-395"><a href="#cb37-395"></a>resample <span class="ot">=</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">size =</span> <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-396"><a href="#cb37-396"></a></span>
<span id="cb37-397"><a href="#cb37-397"></a>dat.plot <span class="ot">=</span> <span class="fu">tibble</span>(resample)</span>
<span id="cb37-398"><a href="#cb37-398"></a></span>
<span id="cb37-399"><a href="#cb37-399"></a><span class="fu">ggplot</span>(dat.plot, <span class="fu">aes</span>(<span class="at">x =</span> resample)) <span class="sc">+</span></span>
<span id="cb37-400"><a href="#cb37-400"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">5</span>)</span>
<span id="cb37-401"><a href="#cb37-401"></a></span>
<span id="cb37-402"><a href="#cb37-402"></a><span class="in">```</span></span>
<span id="cb37-403"><a href="#cb37-403"></a></span>
<span id="cb37-404"><a href="#cb37-404"></a>Our data actually look skewed here as well. So even in this scenario, the researcher should not have done a t-test!</span>
<span id="cb37-405"><a href="#cb37-405"></a></span>
<span id="cb37-406"><a href="#cb37-406"></a></span>
<span id="cb37-407"><a href="#cb37-407"></a><span class="fu">## Part e </span></span>
<span id="cb37-408"><a href="#cb37-408"></a></span>
<span id="cb37-409"><a href="#cb37-409"></a>For each hypothesis test in the previous question, plot the null $T$ </span>
<span id="cb37-410"><a href="#cb37-410"></a>distribution and the observed $t$ statistic. Ensure to use \texttt{geom<span class="sc">\_</span>ribbon()} </span>
<span id="cb37-411"><a href="#cb37-411"></a>to highlight the rejection region and the $p$-value. Additionally, add the </span>
<span id="cb37-412"><a href="#cb37-412"></a>resampling distribution for $T$ to the chart to demonstrate any differences </span>
<span id="cb37-413"><a href="#cb37-413"></a>between the null distribution and the distribution suggested by the data.</span>
<span id="cb37-414"><a href="#cb37-414"></a></span>
<span id="cb37-415"><a href="#cb37-415"></a>**Solution**</span>
<span id="cb37-416"><a href="#cb37-416"></a></span>
<span id="cb37-417"><a href="#cb37-417"></a>***For the farther values:***</span>
<span id="cb37-418"><a href="#cb37-418"></a></span>
<span id="cb37-421"><a href="#cb37-421"></a><span class="in">```{r}</span></span>
<span id="cb37-422"><a href="#cb37-422"></a><span class="co">#| label: fig-histweird</span></span>
<span id="cb37-423"><a href="#cb37-423"></a><span class="co">#| fig-cap: t-distributions for the farther values and the resampling distribution</span></span>
<span id="cb37-424"><a href="#cb37-424"></a></span>
<span id="cb37-425"><a href="#cb37-425"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb37-426"><a href="#cb37-426"></a></span>
<span id="cb37-427"><a href="#cb37-427"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb37-428"><a href="#cb37-428"></a></span>
<span id="cb37-429"><a href="#cb37-429"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">12</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb37-430"><a href="#cb37-430"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-431"><a href="#cb37-431"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)  <span class="co"># centered at observed t</span></span>
<span id="cb37-432"><a href="#cb37-432"></a></span>
<span id="cb37-433"><a href="#cb37-433"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb37-434"><a href="#cb37-434"></a></span>
<span id="cb37-435"><a href="#cb37-435"></a>resample_t <span class="ot">&lt;-</span> (resample <span class="sc">-</span> <span class="fu">mean</span>(dat.kasdin<span class="sc">$</span>Farther.vals)) <span class="sc">/</span> </span>
<span id="cb37-436"><a href="#cb37-436"></a>              (<span class="fu">sd</span>(dat.kasdin<span class="sc">$</span>Farther.vals) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb37-437"><a href="#cb37-437"></a></span>
<span id="cb37-438"><a href="#cb37-438"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb37-439"><a href="#cb37-439"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb37-440"><a href="#cb37-440"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-441"><a href="#cb37-441"></a>  <span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(resample_t),</span>
<span id="cb37-442"><a href="#cb37-442"></a>                 <span class="fu">aes</span>(<span class="at">x =</span> resample_t, <span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb37-443"><a href="#cb37-443"></a>                 <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>, <span class="at">bins =</span> <span class="dv">6</span>,</span>
<span id="cb37-444"><a href="#cb37-444"></a>                 <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb37-445"><a href="#cb37-445"></a><span class="in">```</span></span>
<span id="cb37-446"><a href="#cb37-446"></a></span>
<span id="cb37-447"><a href="#cb37-447"></a></span>
<span id="cb37-448"><a href="#cb37-448"></a>Here, we see the null t-distribution, the t-distribution shifted to be centered at our observed t-statistic, and the histogram of our resampling distribution standardized to be on the t-scale. I realize that I may have interpreted the earlier instructions for resampling wrong, and maybe it was suppoed to be bootstrapping, but I had guidance from Professor Cipolli during lab that suggested that this was correct. This histogram-scaling approach might be the correct answer, but it also isn't something I've seen before. I am including it here because I am not sure exactly why it would be incorrect (if it is incorrect), and I look forward to getting feedback!</span>
<span id="cb37-449"><a href="#cb37-449"></a></span>
<span id="cb37-450"><a href="#cb37-450"></a>Also, the graph with bootstrapping:</span>
<span id="cb37-451"><a href="#cb37-451"></a></span>
<span id="cb37-454"><a href="#cb37-454"></a><span class="in">```{r}</span></span>
<span id="cb37-455"><a href="#cb37-455"></a><span class="co">#| label: fig-farther1</span></span>
<span id="cb37-456"><a href="#cb37-456"></a><span class="co">#| fig-cap: t-distributions for the farther values</span></span>
<span id="cb37-457"><a href="#cb37-457"></a></span>
<span id="cb37-458"><a href="#cb37-458"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb37-459"><a href="#cb37-459"></a></span>
<span id="cb37-460"><a href="#cb37-460"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb37-461"><a href="#cb37-461"></a></span>
<span id="cb37-462"><a href="#cb37-462"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">12</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb37-463"><a href="#cb37-463"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-464"><a href="#cb37-464"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)  <span class="co"># centered at observed t</span></span>
<span id="cb37-465"><a href="#cb37-465"></a></span>
<span id="cb37-466"><a href="#cb37-466"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb37-467"><a href="#cb37-467"></a></span>
<span id="cb37-468"><a href="#cb37-468"></a>boot_t_far <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb37-469"><a href="#cb37-469"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Farther.vals, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-470"><a href="#cb37-470"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb37-471"><a href="#cb37-471"></a>})</span>
<span id="cb37-472"><a href="#cb37-472"></a></span>
<span id="cb37-473"><a href="#cb37-473"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb37-474"><a href="#cb37-474"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb37-475"><a href="#cb37-475"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-476"><a href="#cb37-476"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_far),</span>
<span id="cb37-477"><a href="#cb37-477"></a>             <span class="fu">aes</span>(<span class="at">x =</span> boot_t_far),</span>
<span id="cb37-478"><a href="#cb37-478"></a>             <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb37-479"><a href="#cb37-479"></a>             <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb37-480"><a href="#cb37-480"></a></span>
<span id="cb37-481"><a href="#cb37-481"></a></span>
<span id="cb37-482"><a href="#cb37-482"></a><span class="in">```</span></span>
<span id="cb37-483"><a href="#cb37-483"></a></span>
<span id="cb37-484"><a href="#cb37-484"></a>With both visualizations, the t-distribution actually appears to be an okay fit for the data. The data are a little more left-skewed, but it's not horrible. </span>
<span id="cb37-485"><a href="#cb37-485"></a></span>
<span id="cb37-486"><a href="#cb37-486"></a>***For the closer values:***</span>
<span id="cb37-487"><a href="#cb37-487"></a></span>
<span id="cb37-488"><a href="#cb37-488"></a></span>
<span id="cb37-491"><a href="#cb37-491"></a><span class="in">```{r}</span></span>
<span id="cb37-492"><a href="#cb37-492"></a><span class="co">#| label: fig-closer1</span></span>
<span id="cb37-493"><a href="#cb37-493"></a><span class="co">#| fig-cap: t-distributions for the closer values</span></span>
<span id="cb37-494"><a href="#cb37-494"></a></span>
<span id="cb37-495"><a href="#cb37-495"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb37-496"><a href="#cb37-496"></a></span>
<span id="cb37-497"><a href="#cb37-497"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb37-498"><a href="#cb37-498"></a></span>
<span id="cb37-499"><a href="#cb37-499"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb37-500"><a href="#cb37-500"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-501"><a href="#cb37-501"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-502"><a href="#cb37-502"></a></span>
<span id="cb37-503"><a href="#cb37-503"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb37-504"><a href="#cb37-504"></a></span>
<span id="cb37-505"><a href="#cb37-505"></a>boot_t_close <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb37-506"><a href="#cb37-506"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Closer.vals, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-507"><a href="#cb37-507"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb37-508"><a href="#cb37-508"></a>})</span>
<span id="cb37-509"><a href="#cb37-509"></a></span>
<span id="cb37-510"><a href="#cb37-510"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb37-511"><a href="#cb37-511"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb37-512"><a href="#cb37-512"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-513"><a href="#cb37-513"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_close),</span>
<span id="cb37-514"><a href="#cb37-514"></a>               <span class="fu">aes</span>(<span class="at">x =</span> boot_t_close),</span>
<span id="cb37-515"><a href="#cb37-515"></a>               <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb37-516"><a href="#cb37-516"></a>               <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb37-517"><a href="#cb37-517"></a><span class="in">```</span></span>
<span id="cb37-518"><a href="#cb37-518"></a></span>
<span id="cb37-519"><a href="#cb37-519"></a>Again, for the closer values, the t-distribution actually appears to be an okay fit for the data. The data are a little more right-skewed, but it's not horrible. </span>
<span id="cb37-520"><a href="#cb37-520"></a></span>
<span id="cb37-521"><a href="#cb37-521"></a></span>
<span id="cb37-522"><a href="#cb37-522"></a>***For the differences:***</span>
<span id="cb37-523"><a href="#cb37-523"></a></span>
<span id="cb37-526"><a href="#cb37-526"></a><span class="in">```{r}</span></span>
<span id="cb37-527"><a href="#cb37-527"></a><span class="co">#| label: fig-diff1</span></span>
<span id="cb37-528"><a href="#cb37-528"></a><span class="co">#| fig-cap: t-distributions for the differences</span></span>
<span id="cb37-529"><a href="#cb37-529"></a></span>
<span id="cb37-530"><a href="#cb37-530"></a><span class="co"># Let's center our t-distribution around our observed t-statistic:</span></span>
<span id="cb37-531"><a href="#cb37-531"></a></span>
<span id="cb37-532"><a href="#cb37-532"></a>t_obs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic</span>
<span id="cb37-533"><a href="#cb37-533"></a></span>
<span id="cb37-534"><a href="#cb37-534"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="fl">0.05</span>)</span>
<span id="cb37-535"><a href="#cb37-535"></a>null_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-536"><a href="#cb37-536"></a>shifted_t <span class="ot">&lt;-</span> <span class="fu">dt</span>(x <span class="sc">-</span> t_obs, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb37-537"><a href="#cb37-537"></a></span>
<span id="cb37-538"><a href="#cb37-538"></a>plot.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, null_t, shifted_t)</span>
<span id="cb37-539"><a href="#cb37-539"></a></span>
<span id="cb37-540"><a href="#cb37-540"></a>boot_t_diff <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb37-541"><a href="#cb37-541"></a>  s <span class="ot">&lt;-</span> <span class="fu">sample</span>(dat.kasdin<span class="sc">$</span>Difference, <span class="at">size =</span> <span class="fu">nrow</span>(dat.kasdin), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-542"><a href="#cb37-542"></a>  (<span class="fu">mean</span>(s) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> (<span class="fu">sd</span>(s) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(dat.kasdin)))</span>
<span id="cb37-543"><a href="#cb37-543"></a>})</span>
<span id="cb37-544"><a href="#cb37-544"></a></span>
<span id="cb37-545"><a href="#cb37-545"></a><span class="fu">ggplot</span>(plot.data, <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb37-546"><a href="#cb37-546"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> null_t), <span class="at">color =</span> <span class="st">"darkorchid"</span>) <span class="sc">+</span></span>
<span id="cb37-547"><a href="#cb37-547"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> shifted_t), <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-548"><a href="#cb37-548"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(boot_t_diff),</span>
<span id="cb37-549"><a href="#cb37-549"></a>               <span class="fu">aes</span>(<span class="at">x =</span> boot_t_diff),</span>
<span id="cb37-550"><a href="#cb37-550"></a>               <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb37-551"><a href="#cb37-551"></a>               <span class="at">color =</span> <span class="st">"gray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb37-552"><a href="#cb37-552"></a></span>
<span id="cb37-553"><a href="#cb37-553"></a><span class="in">```</span></span>
<span id="cb37-554"><a href="#cb37-554"></a></span>
<span id="cb37-555"><a href="#cb37-555"></a>Again, for the differences, the t-distribution actually appears to be an okay fit for the data. The data are a little more right-skewed, but it's not horrible. </span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Hudson Miller · Colgate University</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>