{
  "hash": "711e9b0ec682c4613cf390f70a7465ac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(\"extraDistr\")\n```\n:::\n\n\n \\normalsize\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nWe use the binomial distribution with $n=3, p=0.70$ to find the probability of Player A winning $\\ge 2$ games: \n\n$$P(X \\ge 2)$$\n\nWe can use the PMF for this because it is a discrete variable, which allows us to find $P(X=0)$ and $P(X=1)$, which we can add together to get $P(X \\ge 2)=1-P(0)-P(1)$. Now that we know how we want to find the answer, let's plot and compute it:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 3\np <- 0.70\nggdat <- tibble(x = -1:13) |>\nmutate(PMF = dbinom(x, size=n, prob=p),\nCDF = pbinom(x, size=n, prob=p))\n\nPMF.plot <- ggplot() +\ngeom_linerange(data = ggdat,\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==0|x==1),\naes(x = x, ymin = 0, ymax = PMF),\ncolor=\"darkorchid2\", linewidth=1.5,alpha=0.5) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Player A wins (x)\",\nbreaks = seq(0, 13, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Player A wins (x)\",\nbreaks = seq(0, 13, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# 1-PMF(0)-PMF(1)\n\n(A_win = 1-dbinom(x = 0, prob = 0.7, size = 3)-dbinom(x = 1, prob = 0.70, size = 3) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe probability of Player A winning is 0.784.\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nThis situation is asking for the number of failures until the second success, but we must limit our amount of trials to 3. The parameters for the negative binomial distribution are $p$ and $r$, in this case we have $p=0.7$ and $r=2$. We are computing the probability that it takes less than or equal to 3 trials for 2 successes to occur. This time, let's use the CDF. We want $P(X \\le 3)$, which corresponds to the CDF evaluated at 1. Let's graph and compute it:\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- 2\np <- 0.70\nggdat <- tibble(x = -1:6) |>\nmutate(PMF = dnbinom(x, size=r, prob=p),\nCDF = pnbinom(x, size=r, prob=p))\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Number of Losses (x)\",\nbreaks = seq(0, 6, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_linerange(data = ggdat |> filter(x==1),\naes(x = x, ymin = 0, ymax = CDF),\ncolor=\"darkorchid2\", linewidth=1.5,alpha=0.5) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Number of Losses (x)\",\nbreaks = seq(0, 6, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# CDF Evaluated at X=1, giving us the probability of 1 failure:\n\npnbinom(q = 1, prob = 0.70, size = 2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe get the same probability of 0.784. Note that the plot goes to 6 trials after which Player A is extremely likely to have won at least 2 games. We only play 3 times, but that is not relevant to the shape of the distribution. Rather, that information is encoded in the fact that we are looking for the probability of 2 successes with at most one failure.\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nggdat <- tibble(x = seq(0,1, length.out=500)) |>\nmutate(PDF = dbeta(x = x, shape1 = alpha, shape2 = beta),\nCDF = pbeta(q = x, shape1 = alpha, shape2 = beta))\n\nPDF.plot <- ggplot(ggdat) +\ngeom_line(aes(x = x, y = PDF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PDF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning one game\",\nbreaks = seq(0, 1, 0.2)) +\nylab(\"Probability\") +\ntheme_bw()\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning one game\",\nbreaks = seq(0, 1, 0.2)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nPDF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe plot on the left represents the density of the probability that Player A will win one game. For example, there is a peak around .7, which means that it is most likely that Player A will have a 70% chance to win one game. The plot on the right represents the probability that Player A will have a probability less than or equal to the x-value for winning one game. For exampe, we interpret the CDF of 1 being 1 because there is a 100% probability that Player A will have a probability of less than or equal to 1 for winning one game.\n\n2. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\n\n# Mean:\n\n(E = (integrate(function(p){\n  p * dbeta(p, shape1 = alpha, shape2 = beta)\n},\n0,1\n))$value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7\n```\n\n\n:::\n\n```{.r .cell-code}\n#Variance:\n\n(var = integrate(function(p){\n  ((p-E)^2)*dbeta(p,alpha,beta)\n},\n0,1))$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01909091\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n$$E(P) = \\mu_P=0.7$$\nand\n$$var(P) = \\sigma^2_P=0.01909091$$\n\n3. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\n**Solution**\n\nThe probability that Player A has a win probability of *exactly* 0.7 is zero. The probability that a continuous distribution is equal to any value is always zero. In other words, the $P(p=0.7)$ will be equal to zero. Let's show this with a plot:\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nggdat <- tibble(x = seq(0,1, length.out=500)) |>\nmutate(PDF = dbeta(x = x, shape1 = alpha, shape2 = beta),\nCDF = pbeta(q = x, shape1 = alpha, shape2 = beta))\n\nPDF.plot <- ggplot(ggdat) +\ngeom_line(aes(x = x, y = PDF)) +\ngeom_hline(yintercept = 0) +\ngeom_ribbon(data = ggdat |> filter(abs(x-0.7)<0.002),\naes(x = x, ymin = 0, ymax = PDF),\ncolor=\"darkorchid2\", alpha=0.5) +\nscale_x_continuous(\"Probability of winning one game\",\nbreaks = seq(0, 1, 0.1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe width of the bar is zero, i.e. we are integrating with our lower bound equal to our upper bound, so our result will be zero.\n\n4. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\nThe probabulity that Player A has a win probability of at least 0.5 is equal to the $1-P(X \\le 0.5)$, and $P(X\\le 0.5)$ is equal to the CDF evaluated at 0.5. Note that the equals is trivial because the distribution is continuous. This is equivalent to the area under the PDF from 0.5 to 1, which is easier to visualize. Let's compute and plot it:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nggdat <- tibble(x = seq(0,1, length.out=500)) |>\nmutate(PDF = dbeta(x = x, shape1 = alpha, shape2 = beta),\nCDF = pbeta(q = x, shape1 = alpha, shape2 = beta))\n\nPDF.plot <- ggplot(ggdat) +\ngeom_line(aes(x = x, y = PDF)) +\ngeom_hline(yintercept = 0) +\ngeom_ribbon(data = ggdat |> filter(x>0.5),\naes(x = x, ymin = 0, ymax = PDF),\ncolor=\"darkorchid2\", alpha = 0.5) +\nscale_x_continuous(\"Probability of winning one game\",\nbreaks = seq(0, 1, 0.1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(prob = 1-pbeta(q = 0.5, shape1 = alpha, shape2 = beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nSo the probability that Player A has at least a probability of 0.5 is 0.9101562. \n\n\n5. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\n**Solution**\n\nWe can use the inverse CDF to find the 90th percentile of Player A's win probability. This requires us to find where the CDF is equal to 0.9. We use the `qbeta` function:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nggdat <- tibble(x = seq(0,1, length.out=500)) |>\nmutate(PDF = dbeta(x = x, shape1 = alpha, shape2 = beta),\nCDF = pbeta(q = x, shape1 = alpha, shape2 = beta))\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\ngeom_ribbon(data = ggdat |> filter(abs(x-0.87)<0.005),\naes(x = x, ymin = 0, ymax = CDF),\ncolor=\"darkorchid2\", alpha = 0.5) +\ngeom_segment(data = ggdat |> filter(abs(x - 0.87) < 0.001),\n  aes(x = 0, xend = 0.87, y = 0.9, yend = 0.9),\n  color = \"gray43\",linewidth = 1.2) +\nscale_x_continuous(\"Probability of winning one game\",\nbreaks = seq(0, 1, 0.2)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(inv = qbeta(p = 0.9, alpha, beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8705027\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe can see that the 90th percentile of Player A's win probability is 0.8705027.\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\n**Solution**\n\nWe use the same logic that we used earlier for the binomial distribution. Using the Beta-Binomial distribution allows us to account for variance in $p$, but we do not need to change any of the probability statement logic because it is still discrete. Let's compute and plot the results:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nggdat <- tibble(x = (0:3)) |>\nmutate(PMF = dbbinom(x = x, size = 3, alpha=alpha, beta=beta),\nCDF = pbbinom(q = x, size = 3, alpha=alpha, beta=beta))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 6, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 6, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n#1-PMF(0)-PMF(1)\n\n(A_win = 1-dbbinom(x = 0, size = 3, alpha, beta)-dbbinom(x = 1, size = 3, alpha, beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe obtain a probability of $0.763636...\\approx 0.764$ that player A wins the match. This is slightly lower than the binomial and the negative binomial result of $0.784$, but similar. This makes sense, as the beta distribution is left-skewed.\n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma^2_X &= \\sum_{i=0}^3 (i-\\mu_X)^2 f_X(i)\n\\end{align*}\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check expected value of Binomial Distribution\n\n\n(mu.binom = 0*dbinom(x= 0, size= 3, prob= 0.7) + 1*dbinom(x= 1, size= 3, prob= 0.7) + 2*dbinom(x= 2, size= 3, prob= 0.7) + 3*dbinom(x= 3, size= 3, prob= 0.7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n(np = 0.7 * 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# We get equality!\n\n# Now, check variance of Binomial Distribution\n\n(var.binom = (0-mu.binom)^2*dbinom(x= 0, size= 3, prob= 0.7)+ (1-mu.binom)^2*dbinom(x= 1, size= 3, prob= 0.7)+ (2-mu.binom)^2*dbinom(x= 2, size= 3, prob= 0.7)+ (3-mu.binom)^2*dbinom(x= 3, size= 3, prob= 0.7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n\n```{.r .cell-code}\n(analytic.var.binom= 3*0.7*(1-0.7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n\n```{.r .cell-code}\n# We get equality!\n\n# Now we check the expected value of the Beta-Binomial Distribution.\n\n\n(mu.bb = 0*dbbinom(x = 0, size = 3, alpha, beta) + 1*dbbinom(x = 1, size = 3, alpha, beta) + 2*dbbinom(x = 2, size = 3, alpha, beta) + 3*dbbinom(x = 3, size = 3, alpha, beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\nn = 3\na = 7\nb = 3\n\n(mu.bb.analytic = n*(a/(a+b)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# We get equality! Note that this is the same as the Binomial Distribution. \n\n# Now we check the variance of the Beta-Binomial Distribution. \n\n(var.bb = (0-mu.bb)^2*dbbinom(x = 0, size = 3, alpha, beta) + (1-mu.bb)^2*dbbinom(x = 1, size = 3, alpha, beta) + (2-mu.bb)^2*dbbinom(x = 2, size = 3, alpha, beta) + (3-mu.bb)^2*dbbinom(x = 3, size = 3, alpha, beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7445455\n```\n\n\n:::\n\n```{.r .cell-code}\n(var.bb.analytic = (n*a*b*(a+b+n))/((a+b)^2*(a+b+1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7445455\n```\n\n\n:::\n\n```{.r .cell-code}\n# We get equality! Notice that this is larger than the variance of the Binomial Distribution, which makes sense.\n```\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom= function(p,theta,n,x){\n  summands = 0:n\n  cvec = c(0)\n  for (i in summands){\n    cvec[i+1] = choose(n,i)*p^i*(1-p)^(n-i) * theta^(i*(n-i))\n    }\n  c=sum(cvec)\n  PMF = (1/c)*choose(n,x)*p^x*(1-p)^(n-x)*theta^(x*(n-x))\nreturn(PMF)\n}\n```\n:::\n\n\n \\normalsize\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 0.5, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 1, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 1.5, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\nA higher theta seems to correspond to a shorter or less potent hot streak, or maybe there is some observed \"cost\" to having a hot streak. We will be able to see better in the next section if probability of winning increases with theta for these values.\n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaltbinom = function(p,theta,n,x){\n  seq = 0:x\n  CDF = sum(daltbinom(p,theta,n,x=seq))\n  return(CDF)\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(CDF =sapply(x, function(k) paltbinom(p=0.7, theta=0.5, n=3, k)))\n\n\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(CDF =sapply(x, function(k) paltbinom(p=0.7, theta=1, n=3, k)))\n\n\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(CDF =sapply(x, function(k) paltbinom(p=0.7, theta=1.5, n=3, k)))\n\n\n\nCDF.plot <- ggplot(ggdat) +\ngeom_step(aes(x = x, y = CDF)) +\ngeom_point(aes(x = x, y = CDF), size = 1) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Cumulative Probability\") +\ntheme_bw()\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nIt appears that a higher theta lowers the probability of Player A winning 0 games, but raises the probability of Player A winning one game. We will see in the next section whether theta has a positive or negative effect on the probability of Player A winning in a best 2-out-of-3 scenario.\n\n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n\n**Solution**\n\nTo solve this, we can use the PMF to find the probability of winning 0 or 1 games and subtract the probability of these outcomes from 1, i.e. $1-F_X(1)-F_X(0)$ \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for theta = 0.5:\n\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 0.5, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2|x==3),\naes(x = x, ymin = 0, ymax = PMF),\ncolor=\"darkorchid2\", linewidth=1.5,alpha=0.5) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbinom(p=0.7, theta=0.5, n=3, x=0) - \n           daltbinom(p=0.7, theta=0.5, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for theta = 1:\n\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 1, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2|x==3),\naes(x = x, ymin = 0, ymax = PMF),\ncolor=\"darkorchid2\", linewidth=1.5,alpha=0.5) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-20-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbinom(p=0.7, theta=1, n=3, x=0) - \n           daltbinom(p=0.7, theta=1, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for theta = 0.5:\n\nggdat <- tibble(x = c(0,1,2,3)) |>\nmutate(PMF = daltbinom(x = x, p = 0.7, theta = 1.5, n=3))\n\n\nPMF.plot <- ggplot(ggdat) +\ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2),\naes(x = x, ymin = 0, ymax = PMF)) +\ngeom_linerange(data = ggdat |> filter(x==2|x==3),\naes(x = x, ymin = 0, ymax = PMF),\ncolor=\"darkorchid2\", linewidth=1.5,alpha=0.5) +\ngeom_hline(yintercept = 0) +\nscale_x_continuous(\"Probability of winning n games\",\nbreaks = seq(0, 3, 1)) +\nylab(\"Probability\") +\ntheme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbinom(p=0.7, theta=1.5, n=3, x=0) - \n           daltbinom(p=0.7, theta=1.5, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.746993\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe get win (Player A wins in a best two-out-of-three scenario ) probabilities of $\\approx 0.86,0.78, \\text{ and } 0.75$ for $\\theta = 0.5,1, \\text{ and } 1.5$, respectively. Our Beta-Binomial result was 0.764, our Negative Binomial result was 0.784, and this was the same as our Binomial result. The Altham distribution is highly dependent on theta, and we get some results with a much greater probability of winning ($\\theta=0.5$), and some results with about the same probability.\n\n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n$$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals. \n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# I don't know why this doesn't look like a code block in the Quarto editor, but it looks fine in the PDF. \n\ndaltbbinom = function(alpha, beta, theta, n, x){\n  integrate(function(p){\n    cvec = rowSums(sapply(0:n, function(i) choose(n,i) * p^i * (1-p)^(n-i) * theta^(i*(n-i))))\n    altham   = (1/cvec) * choose(n,x) * p^x * (1-p)^(n-x) * theta^(x*(n-x))\n    beta.pdf = dbeta(p, alpha, beta)\n    altham * beta.pdf\n  }, lower = 0, upper = 1)$value\n}\n```\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# theta = 0.5\nggdat <- tibble(x = c(0,1,2,3)) |>\n  mutate(PMF = sapply(x, function(k)\n    daltbbinom(alpha=7, beta=3, theta=0.5, n=3, x=k)))\n\nPMF.plot <- ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x==2|x==3),\n    aes(x = x, ymin = 0, ymax = PMF),\n    color=\"darkorchid2\", linewidth=1.5, alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Probability of winning n games\",\n    breaks = seq(0, 3, 1)) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbbinom(alpha=7, beta=3, theta=0.5, n=3, x=0) -\n             daltbbinom(alpha=7, beta=3, theta=0.5, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8081866\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# theta = 1\nggdat <- tibble(x = c(0,1,2,3)) |>\n  mutate(PMF = sapply(x, function(k)\n    daltbbinom(alpha=7, beta=3, theta=1, n=3, x=k)))\n\nPMF.plot <- ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x==2|x==3),\n    aes(x = x, ymin = 0, ymax = PMF),\n    color=\"darkorchid2\", linewidth=1.5, alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Probability of winning n games\",\n    breaks = seq(0, 3, 1)) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbbinom(alpha=7, beta=3, theta=1, n=3, x=0) -\n             daltbbinom(alpha=7, beta=3, theta=1, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# theta = 1.5\nggdat <- tibble(x = c(0,1,2,3)) |>\n  mutate(PMF = sapply(x, function(k)\n    daltbbinom(alpha=7, beta=3, theta=1.5, n=3, x=k)))\n\nPMF.plot <- ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x==2|x==3),\n    aes(x = x, ymin = 0, ymax = PMF),\n    color=\"darkorchid2\", linewidth=1.5, alpha=0.5) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Probability of winning n games\",\n    breaks = seq(0, 3, 1)) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n(A_win = 1 - daltbbinom(alpha=7, beta=3, theta=1.5, n=3, x=0) -\n             daltbbinom(alpha=7, beta=3, theta=1.5, n=3, x=1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7387904\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe now get a tighter spread for the variance with theta. Our probabilities are $\\approx 0.81,0.76, \\text{ and } 0.74$ for $\\theta = 0.5,1, \\text{ and } 1.5$, respectively. This clusters cloesly around our results for the other distributions.\n\n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n* **Negative Binomial**\\\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n* **Beta-Binomial**\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\n**Solution**\n\nThis seems easy to write a function for, but this is one of those examples where the long way is the short way. The need to distinguish between the third and fourth cases make this complicated. This approach also is very easy to analyze what is going on in terms of the probability statements. We check each distribution to make sure the sum of all outcomes is 1. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Binomial:\nprob_binom = c(0)\n\nprob_binom[1] = dbinom(x=0, prob=0.7, size=2)            # Lose 0-2\nprob_binom[2] = dbinom(x=1, prob=0.7, size=2) * (1-0.7) # Lose 1-2\nprob_binom[3] = dbinom(x=2, prob=0.7, size=2)            # Win 2-0\nprob_binom[4] = dbinom(x=1, prob=0.7, size=2) * 0.7      # Win 2-1\n\nsum(prob_binom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Negative Binomial:\nprob_nbinom = c(0)\n\nprob_nbinom[1] = dbinom(x=0, prob=0.7, size=2)            # Lose 0-2\nprob_nbinom[2] = dbinom(x=1, prob=0.7, size=2) * (1-0.7) # Lose 1-2\nprob_nbinom[3] = dbinom(x=2, prob=0.7, size=2)            # Win 2-0\nprob_nbinom[4] = dbinom(x=1, prob=0.7, size=2) * 0.7      # Win 2-1\n\nsum(prob_nbinom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Beta-Binomial:\nprob_bbinom = c(0)\n\nprob_bbinom[1] = dbbinom(x=0, size=2, alpha=7, beta=3)             # Lose 0-2\nprob_bbinom[2] = dbbinom(x=1, size=2, alpha=7, beta=3) * (3/(7+3)) # Lose 1-2\nprob_bbinom[3] = dbbinom(x=2, size=2, alpha=7, beta=3)             # Win 2-0\nprob_bbinom[4] = dbbinom(x=1, size=2, alpha=7, beta=3) * (7/(7+3)) # Win 2-1\n\n# NOTE: the $3/(7+3)$ is derived from the expected win probability of the Beta-Binomial distribution (alpha divided by alpha plus beta) for one game. We saw this formula in section 2.3. We use this again for Altham's Beta-Binomial. \n\nsum(prob_bbinom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Altham Binomial, theta = 0.5:\nprob_altham05 = c(0)\n\nprob_altham05[1] = daltbinom(p=0.7, theta=0.5, n=2, x=0)            # Lose 0-2\nprob_altham05[2] = daltbinom(p=0.7, theta=0.5, n=2, x=1) * (1-0.7) # Lose 1-2\nprob_altham05[3] = daltbinom(p=0.7, theta=0.5, n=2, x=2)            # Win 2-0\nprob_altham05[4] = daltbinom(p=0.7, theta=0.5, n=2, x=1) * 0.7     # Win 2-1\n\nsum(prob_altham05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Altham Binomial, theta = 1.5:\nprob_altham15 = c(0)\n\nprob_altham15[1] = daltbinom(p=0.7, theta=1.5, n=2, x=0)            # Lose 0-2\nprob_altham15[2] = daltbinom(p=0.7, theta=1.5, n=2, x=1) * (1-0.7) # Lose 1-2\nprob_altham15[3] = daltbinom(p=0.7, theta=1.5, n=2, x=2)            # Win 2-0\nprob_altham15[4] = daltbinom(p=0.7, theta=1.5, n=2, x=1) * 0.7     # Win 2-1\n\nsum(prob_altham15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Altham Beta-Binomial, theta = 0.5:\nprob_althambb05 = c(0)\n\nprob_althambb05[1] = daltbbinom(alpha=7, beta=3, theta=0.5, n=2, x=0)              # Lose 0-2\nprob_althambb05[2] = daltbbinom(alpha=7, beta=3, theta=0.5, n=2, x=1) * (3/(7+3)) # Lose 1-2\nprob_althambb05[3] = daltbbinom(alpha=7, beta=3, theta=0.5, n=2, x=2)              # Win 2-0\nprob_althambb05[4] = daltbbinom(alpha=7, beta=3, theta=0.5, n=2, x=1) * (7/(7+3)) # Win 2-1\n\nsum(prob_althambb05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Altham Beta-Binomial, theta = 1.5:\nprob_althambb15 = c(0)\n\nprob_althambb15[1] = daltbbinom(alpha=7, beta=3, theta=1.5, n=2, x=0)              # Lose 0-2\nprob_althambb15[2] = daltbbinom(alpha=7, beta=3, theta=1.5, n=2, x=1) * (3/(7+3)) # Lose 1-2\nprob_althambb15[3] = daltbbinom(alpha=7, beta=3, theta=1.5, n=2, x=2)              # Win 2-0\nprob_althambb15[4] = daltbbinom(alpha=7, beta=3, theta=1.5, n=2, x=1) * (7/(7+3)) # Win 2-1\n\nsum(prob_althambb15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nplotting.dat = tibble(\n  outcome = rep(c(\"Lose 0-2\", \"Lose 1-2\", \"Win 2-0\", \"Win 2-1\"), 7),\n  prob    = c(prob_binom, prob_nbinom, prob_bbinom,\n              prob_altham05, prob_altham15,\n              prob_althambb05, prob_althambb15),\n  dist    = rep(c(\"Binomial\", \"Negative Binomial\", \"Beta-Binomial\",\n                  \"Altham (t=0.5)\", \"Altham (t=1.5)\",\n                  \"Altham BB (t=0.5)\", \"Altham BB (t=1.5)\"), each=4)\n)\n\nggplot(plotting.dat) +\n  geom_col(aes(x = outcome, y = prob, fill = dist),\n           position = \"dodge\") +\n  scale_x_discrete(limits = c(\"Lose 0-2\", \"Lose 1-2\", \"Win 2-1\", \"Win 2-0\")) +\n  ylab(\"Probability\") +\n  scale_fill_brewer(palette = \"Dark2\", name = \"Distribution\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# This plot was informed by a lot of internet searches and minimal AI help \n# (just the scale_x_discrete and the scale_fill_brewer). \n# I really like the way it looks \n# and I will probably come back to this for plotting anything similar.\n```\n:::\n\n\n \\normalsize\n\nThe Binomial and Negative Binomial distributions are identical. The Beta-Binomial distributions have a higher probability of more \"extreme\" values, as their variance is higher (and, notably, they are also more left-skewed). Altham's for low theta, and then for larger theta, have the most extreme distributions. Low theta expects very extreme values, and high theta expects very moderate values. The same follows for Altham's Beta-Binomial distributions.",
    "supporting": [
      "Lab8WriteUp_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}